build_linux:
  stage: build
  # image: electronuserland/builder:latest
  # image sha256:6e775ff04e58753528ab9fd97d30c204769a0be83fd70f77976a257052203420
  image: electronuserland/builder@sha256:9cfae60a63e04335ca9de37da094e305e38925999576c6dc8f0d09821d271760 
  timeout: 30m
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-linux
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-linux"
    paths:
      - dist-native/*.tar.gz
      - dist-native/*.AppImage
      - dist-native/*.deb

build_win:
  stage: build
  # image: electronuserland/builder:wine
  # image sha256:f134220d2788625df6c54164dc67ffad04e1a964a60b1fff176485c142056f88
  image: electronuserland/builder@sha256:8dd62ce3f32421abbb275d6b721f7ce4377c8442d703c0309cf423a4123997e0
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-win
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-win"
    paths:
      - dist-native/*.exe
      - dist-native/*.zip

build_mac:
  stage: build
  image: blocknetdx/devbuilds:blockdx-gitlab-mac
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-mac
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-mac"
    paths:
      - dist-native/mac/BLOCK DX.app

test_artifacts:
  stage: test
  image: ubuntu:bionic
  script:
    - "set -- dist-native/BLOCK-DX-*-linux-x64.tar.gz && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-x86_64.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-armv7l.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-amd64.deb && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win.exe && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win-x64.zip && [[ -f \"$1\" ]]"
    - "set -- dist-native/mac/BLOCK*DX.app && [[ -d \"$1\" ]]"
